version: '3'

services:
  python:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: python
    ports:
      - "5000"
    external_links:
      - db
      - elasticsearch
      - redis
