version: '3'

##Create service python
services:
  python:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - "./app:/app"
    container_name: python
    ports:
      - "5000"
    external_links:
      - db
      - elasticsearch
      - redis
##Connect python to the same network as the others images
networks:
  default:
    external:
      name: mycompose_default
      
## This is a push for Jenkins 
