version: '3'

services:
  python:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: python
    ports:
      - "5000"
    external_links:
      - mycompose_db_1
      - mycompose_elasticsearch_1
      - mycompose_redis_1
